/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_relicemxd_jnidemo_ndk_JniUtils */

#ifndef _Included_com_relicemxd_jnidemo_ndk_JniUtils
#define _Included_com_relicemxd_jnidemo_ndk_JniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_relicemxd_jnidemo_ndk_JniUtils
 * Method:    getStringFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_relicemxd_jnidemo_ndk_JniUtils_getStringFromC
        (JNIEnv *, jobject);

/*
 * Class:     com_relicemxd_jnidemo_ndk_JniUtils
 * Method:    insertSort
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_com_relicemxd_jnidemo_ndk_JniUtils_insertSort
        (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
